spring:
  application:
    name: dubbo-auto-configure-consumer-sample
server:
  port: 8888

embedded:
  zookeeper:
    port: 2181

demo:
  service:
    version: 1.0.0


dubbo:
  registry:
    address: zookeeper://101.133.149.61:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  scan:
    base-packages: com.onlyedu.consumer.service
  config-center:
    timeout: 40000

